---

- include_vars: "../vars/{{ level }}.yml"
  when: level is defined
  tags:
    - deployment
    - frontend
    - frontend_deployment
    - web

- name: Check out frontend app from its repository
  git: >
      repo=https://github.com/dpla/frontend.git
      dest=/home/dpla/frontend
      version={{ frontend_branch_or_tag }}
  sudo_user: dpla
  when: not frontend_use_local_source
  tags:
    - deployment
    - frontend
    - frontend_deployment
    - web

- name: Check out frontend app from mounted directory
  script: copy_local_app.sh
  when: frontend_use_local_source
  tags:
    - deployment
    - frontend
    - frontend_deployment
    - web

- name: Update frontend app database configuration
  template: >
      src=database.yml.j2 dest=/home/dpla/frontend/config/database.yml
      owner=dpla group=webapp mode=0640
  when: not frontend_use_local_source
  tags:
    - deployment
    - frontend
    - frontend_deployment
    - web

- name: Update frontend app settings
  template: >
      src=settings.local.yml.j2 dest=/home/dpla/frontend/config/settings.local.yml
      owner=dpla group=webapp mode=0640
  when: not frontend_use_local_source
  tags:
    - deployment
    - frontend
    - frontend_deployment
    - web

- name: Update frontend unicorn.rb
  template: >
      src=unicorn.rb.j2 dest=/home/dpla/frontend/config/unicorn.rb
      owner=dpla group=dpla mode=0644
  tags:
    - deployment
    - frontend
    - frontend_deployment
    - web

- name: Make sure rbenv and bundler are current
  script: >
      ../../../files/install_ruby_tools.sh {{ ruby_rbenv_version }}
  sudo_user: dpla
  tags:
    - deployment
    - frontend
    - frontend_deployment
    - web

- name: Ensure existence of live app directory
  file: path=/srv/www/frontend state=directory owner=dpla group=dpla mode=0755
  tags:
    - deployment
    - frontend
    - frontend_deployment
    - web

- name: Ensure existence of frontend/tmp directory
  file: path=/srv/www/frontend/tmp state=directory owner=dpla group=dpla mode=0755
  tags:
    - deployment
    - frontend
    - frontend_deployment
    - web

# Krazy hijinx ensue to get around having a private GitHub repo for the frontend
# assets gem...

- name: Temporarily copy private key for GitHub
  # This will be used by build_frontend.sh
  copy: >
      src={{ github_private_key_path | default("~/.ssh/id_rsa") }}
      dest=/home/dpla/git_private_key
      owner=dpla group=dpla mode=0600
  when: frontend_use_restricted_assets
  tags:
    - deployment
    - frontend
    - frontend_deployment
    - web

- name: Stop Unicorn (gracefully)
  # Unicorn is stopped completely, and later restarted, because we assume that
  # preload_app is true, and this option means that a SIGHUP to reload Unicorn's
  # configuration won't cause it to reload program code.  In a setting other than
  # development, the NGINX reverse-proxy in front of Unicorn will be routing requests
  # to the other servers in the same pool.
  service: name=unicorn_frontend state=stopped
  tags:
    - deployment
    - frontend
    - frontend_deployment
    - web

- name: Build frontend app
  script: >-
      build_frontend.sh {{ ruby_rbenv_version }}
      {{ 'restricted' if frontend_use_restricted_assets else 'unrestricted' }}
  sudo_user: dpla
  tags:
    - deployment
    - frontend
    - frontend_deployment
    - web

- name: Ensure existence of uploads directory
  file: >-
      path=/srv/www/frontend/public/uploads state=directory
      owner=www-data group=www-data mode=0755
  tags:
    - deployment
    - frontend
    - frontend_deployment
    - web

- name: Clear site proxy cache
  command: find /var/cache/nginx -type f -delete
  delegate_to: "{{ item }}"
  with_items: groups.site_proxies
  tags:
    - deployment
    - frontend
    - frontend_deployment
    - web

- name: Start Unicorn
  service: name=unicorn_frontend state=started
  tags:
    - deployment
    - frontend
    - frontend_deployment
    - web

- name: Remove temporary private key for GitHub
  file: path=/home/dpla/git_private_key state=absent
  when: frontend_use_restricted_assets
  tags:
    - deployment
    - frontend
    - frontend_deployment
    - web

