---

- name: Ensure state of redis package
  apt: name=redis-server state=present

- name: Ensure state of redis configuration file
  template: src=redis.conf.j2 dest=/etc/redis/redis.conf mode=0644
  notify:
    - restart redis
