---

- name: Gather ec2 facts
  ec2_facts:
  when: level == 'production' or level == 'staging'
- name: De-register instance from loadbalancer
  local_action: ec2_elb
  when: level == 'production' or level == 'staging'
  sudo: false
  args:
    instance_id: "{{ ansible_ec2_instance_id }}"
    ec2_elbs: "{{ api_elb_name }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_region: "{{ aws_region }}"
    state: absent
# TODO:  when Ansible 1.8 is released, enable the following
# and require Ansible 1.8.
# - name: Wait for connections to drain
#   sudo: false
#   local_action: >-
#       wait_for host="{{ inventory_hostname }}" port="{{ api_app_port }}"
#       state=drained timeout=60
