---

do_wordpress: false
wp_theme_use_local_source: false

wp_auth_key:        "bLGFW(pi3@m&[HtB4-Utj2+%bwntE kRwex=I#+_G>-mkJVv[X#XYVv9Sg7OV|+j"
wp_secure_auth_key: "iB/:bGNU|7-|4!@u~69:lPWqD)om*g?G=%?nJ,W+:zbet{,Wzm-_aQN^,/DeALm|"
wp_logged_in_key:   "BGr[{r9bj_x&WNmz/tBUwHhS-(b$+|R)@q<wv<[Pe,p)L>H]:8kux2dY^wTavO^S"
wp_nonce_key:       "&b!~D9|&-V|3q~yVn{<#IFft$)8rKeJ>RoNQ]ig&w!fQ9WDeAx%=Ci` 8pjW6Y`|"
wp_auth_salt:       ")=d{XACbc/^+q<,r`L`q]R$1rA)!D{XgG^kmTAI#f3h`-yF>&U#/]);sN;EP&@tQ"
wp_secure_auth_salt: "|6lyuZV=2s~LL]w91$*xtcOm(ZeaL,E^Q$-L{G: IgMp-T6| $aij}+],x7+4:~f"
wp_logged_in_salt:   "Z?.WWr]I;Bu;^!=P ]BK?<x[%lNL*47MWa4=+)4SP7aV21;$<J!g{0m*Q;=3s&q8"
wp_nonce_salt:       "-DV|s.W8/BL^ZP>tz.d2b<KZ9}PxQg.lB13i+)MAvr[+c3+bqbl.OKQA&SZNe*+*"
