---

- name: Set hostname
  hostname: name={{ hostname }}
  tags:
    - networking

- name: Update hosts file
  # This works with "ansible-playbook" but not running from Vagrant, because
  # ansible-playbook will have spoken with all nodes in parallel with the
  # above task, and "vagrant provision" may not have.
  # Note also that it won't work if you use -l / --limit with ansible-playbook
  # to limit the hosts, becuase, in that case, not all hosts will have been
  # contacted.  I will implement a workaround for this, soon.
  template: src="hosts.j2" dest="/etc/hosts"
  tags:
    - networking

- name: Update apt package index
  apt: update_cache=yes
  tags:
    - packages

- name: Upgrade apt packages
  apt: upgrade=safe
  tags:
    - packages

- name: Ensure correct time zone
  shell: >
      echo {{ iana_timezone }} > /etc/timezone; dpkg-reconfigure --frontend noninteractive tzdata
  tags:
    - packages
    - time

- name: Install packages
  apt: pkg={{ item }} state=present
  with_items:
    - make
    - curl
    - sysstat
    - python-httplib2
  tags:
    - packages

- name: Copy sysstat init defaults file
  copy: src=etc_default_sysstat dest=/etc/default/sysstat owner=root group=root mode=0644
  notify: restart sysstat
  tags:
    - packages

- name: Add admin accounts
  user: name="{{ item.username }}" comment="{{ item.gecos }}" state=present
        groups=admin,sudo shell=/bin/bash
  with_items: adminusers
  tags:
    - users

- name: Assign SSH authorized keys
  authorized_key: user="{{ item.username }}" key="{{ item.ssh_authorized_key }}"
  with_items: adminusers
  tags:
    - authorized_keys
    - users

- name: Update SSH client configuration
  copy: src=ssh_config dest=/etc/ssh/ssh_config owner=root group=root mode=0644
  tags:
    - packages

- name: Update systemwide SSH known hosts
  copy: >
      src=etc_ssh_ssh_known_hosts dest=/etc/ssh/ssh_known_hosts
      owner=root group=root mode=0644
  tags:
    - ssh

- name: Ensure that users of 'admin' group can sudo without password
  copy: >
      src=etc_sudoers.d_exempt-group dest=/etc/sudoers.d/10-exempt-group
      owner=root group=root mode=0440
  tags:
    - sudo
    - users

