---

- name: Ensure that privsep account exists for exports
  user: >-
      name=exporter comment="Privilege separtion user for export files"
      home=/home/exporter shell=/bin/bash state=present

- name: Ensure that AWS CLI is installed
  pip: name=awscli state=present

- name: Ensure state of AWS CLI configuration directory
  file: >-
    path=/home/exporter/.aws state=directory owner=exporter group=exporter
    mode=0700

- name: Ensure state of AWS CLI credentials file
  template: >-
    src=aws_credentials.j2 dest=/home/exporter/.aws/credentials
    owner=exporter group=exporter mode=0600

- name: Ensure state of AWS CLI config file
  template: >-
    src=aws_config.j2 dest=/home/exporter/.aws/config
    owner=exporter group=exporter mode=0600

- name: Ensure that node and npm are installed for elasticdump Node package
  apt: >-
    pkg="{{ item }}" state=present
  with_items:
    - nodejs
    - npm
    - jq

# See https://lists.debian.org/debian-devel-announce/2012/07/msg00002.html
# See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=614907
- name: Symlink node binary
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

- name: Ensure that elasticdump is installed
  npm: name=elasticdump version=0.8.1 global=yes

- name: Ensure state of export script
  copy: >-
    src=export-provider.sh dest=/usr/local/bin/export-provider.sh
    owner=root group=root mode=0755

- name: Ensure state of crontab file for exports
  template: >-
    src=etc_cron.d_export-providers.j2 dest=/etc/cron.d/export-providers
    owner=root group=root mode=0644

