---

- include_vars: "../vars/{{ level }}.yml"
  when: level is defined
  tags:
    - munin_master
    - packages
    - scripts

- name: Ensure existence of munin package
  apt: package=munin state=present
  tags:
    - munin_master
    - packages

- name: Ensure state of munin master configuration file
  template: >
      src=munin.conf.j2
      dest=/etc/munin/munin.conf
      owner=root group=root mode=0644
  tags:
    - munin_master
  # Nothing to restart because the master process runs on cron.

- name: Install notify_slack_munin.sh script
  when: slack_webhook_url is defined and slack_channel is defined
  template: >-
      src=notify_slack_munin.sh.j2 dest=/usr/local/bin/notify_slack_munin
      owner=root group=root mode=0755
  tags:
    - munin_master
    - scripts

- name: Enable Munin stats plugins
  file: >-
      src=/usr/share/munin/plugins/{{ item }}
      dest=/etc/munin/plugins/{{ item }}
      state=link owner=root group=root
  with_items:
    - munin_stats
    - munin_update
  notify: restart munin node
