---

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: API (platform) application
  hosts: api
  serial: 1
  sudo: yes
  roles:
    - api
  pre_tasks:
    - include: pre_post_tasks/api_pretasks.yml
  post_tasks:
    - include: pre_post_tasks/api_posttasks.yml
  vars_files:
    - ["../vars/{{ level }}.yml", "../vars/defaults.yml"]
