---

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: Deploy API (staging)
  hosts: api
  sudo: yes
  serial: 1
  pre_tasks:
    - include: pre_post_tasks/api_pretasks.yml
  tasks:
    - include: ../roles/api/tasks/deploy.yml
  post_tasks:
    - include: pre_post_tasks/api_posttasks.yml
  handlers:
    - include: ../roles/api/handlers/main.yml
  vars:
    level: staging
  vars_files:
    - "../vars/staging.yml"
    - "../roles/api/defaults/main.yml"
    - "../roles/api/vars/staging.yml"
