---

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: Exhibitions
  hosts: exhibitions
  sudo: yes
  serial: 1
  roles:
    - omeka
  vars:
    skip_configuration: false
    do_deployment: true
