---

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: Frontend (portal) site
  hosts: frontend
  sudo: yes
  roles:
    - frontend
  vars_files:
    - ["../vars/{{ level }}.yml", "../vars/defaults.yml"]
