---

# To run standalone, specify
# --extra-vars "level=<development|staging|production>"

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: Marmotta
  hosts:
    - marmotta
  sudo: yes
  roles:
    - { role: marmotta, tags: ['marmotta']}
