---

# To run standalone, specify
# --extra-vars "level=<development|staging|production|contentqa>"
# ... or see one of the convenience playbooks that includes this one with the
#     correct value.

- name: Gather inventory facts in case playbook is run standalone
  hosts: all


- name: MySQL
  hosts: mysql_dbs
  sudo: yes
  roles:
    - mysql
  vars_files:
    - ["../vars/{{ level }}.yml", "../vars/defaults.yml"]
