---

- name: MySQL
  hosts: mysql_dbs
  sudo: yes
  roles:
    - mysql
  vars:
    # Default to production to keep development values from accidentally being
    # used in production.
    level: production
  vars_files:
    - ["../vars/{{ level }}.yml", "../vars/defaults.yml"]
