---

- include: pg_maintenance_on.yml

- name: Reboot PostgreSQL server
  hosts: postgresql_dbs
  sudo: true
  tasks:
    - name: Reboot
      command: /sbin/shutdown -r now
      async: 0
      poll: 0
      ignore_errors: true
    - name: Wait for it to come back up
      sudo: false
      local_action: >-
        wait_for host="{{ inventory_hostname }}"
        port=5432 delay=40 timeout=600

- include: pg_maintenance_off.yml
