---

- name: restart nginx
  service: name=nginx state=restarted

- name: restart php5-fpm
  service: name=php5-fpm state=restarted

- name: clear site proxy cache
  command: find /var/cache/nginx -type f -delete
  delegate_to: "{{ item }}"
  with_items: groups.site_proxies
