---

exhibitions_branch_or_tag: "v16.1"

# PHP-FPM tuning parameters
omeka_php_max_children: 10
omeka_php_start_servers: 2
omeka_php_min_spare_servers: 2
omeka_php_max_spare_servers: 4
omeka_php_max_requests: 500
