---

- name: Common
  hosts: all
  sudo: yes
  roles:
    - common

- include: playbooks/dev_loadbalancer.yml

- include: playbooks/dbnodes.yml

- include: playbooks/elasticsearch.yml

- include: playbooks/dev_webapps.yml
